import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/session";
import { getSettings } from "@/lib/settings";
import { getReportTable, reportMeta, parseReportFilters } from "@/lib/reports";
import { docColor, DOC_THEME } from "@/lib/docTheme";
import { fmt, fmtDate } from "@/lib/format";
import AutoPrint from "@/components/reports/AutoPrint";

export const dynamic = "force-dynamic";

const STATUS_COLOR: Record<string, string> = { approved: DOC_THEME.brand, pending: "#C77300", missing: "#DC2626" };

function cellText(val: string | number, isNumeric: boolean): string {
  if (isNumeric && typeof val === "number") return fmt(val);
  return String(val);
}

export default async function PrintReportPage({ params, searchParams }: { params: Promise<{ type: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const user = await getCurrentUser();
  if (!user) redirect("/login");

  const { type } = await params;
  const sp = await searchParams;
  const usp = new URLSearchParams(Object.entries(sp).flatMap(([k, v]) => (v === undefined ? [] : [[k, Array.isArray(v) ? v[0] : v] as [string, string]])));
  const filters = parseReportFilters(usp);
  const [table, settings, meta] = await Promise.all([getReportTable(type, filters), getSettings(), Promise.resolve(reportMeta(type))]);
  const brand = docColor(meta.color);

  return (
    <div style={{ fontFamily: "var(--sans, system-ui, sans-serif)", color: DOC_THEME.text, maxWidth: 900, margin: "0 auto", padding: "0 0 40px" }}>
      <style>{`
        @media print {
          .no-print { display: none !important; }
          @page { margin: 14mm; }
          body { background: #fff; }
        }
        body { background: #f3f5f4; }
      `}</style>

      <div className="no-print" style={{ height: 14 }} />

      <div style={{ background: `linear-gradient(135deg, ${brand}, ${DOC_THEME.brandDark})`, borderRadius: 10, padding: "22px 26px", display: "flex", alignItems: "center", gap: 16, color: "#fff" }}>
        {settings.companyLogo ? (
          <img src={settings.companyLogo} alt={settings.companyName} style={{ width: 52, height: 52, objectFit: "contain", background: "#fff", borderRadius: 8, padding: 4 }} />
        ) : null}
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 20, fontWeight: 700 }}>{settings.companyName}</div>
          <div style={{ fontSize: 13, opacity: 0.9, marginTop: 2 }}>{table.title} — {table.subtitle}</div>
        </div>
        <div style={{ textAlign: "right", fontSize: 11.5, opacity: 0.9 }}>
          <div>Generated {fmtDate(table.generatedAt)}</div>
          <div>By {user.name}</div>
        </div>
      </div>

      <table style={{ width: "100%", borderCollapse: "collapse", marginTop: 22, fontSize: 13 }}>
        <thead>
          <tr>
            {table.columns.map((c, i) => (
              <th key={c} style={{ background: brand, color: "#fff", textAlign: table.numericCols.includes(i) ? "right" : "left", padding: "9px 12px", fontWeight: 600, fontSize: 12 }}>{c}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {table.rows.map((row, ri) => (
            <tr key={ri} style={{ background: ri % 2 === 1 ? DOC_THEME.bandFill : "transparent" }}>
              {row.map((val, ci) => {
                const isStatus = table.columns[ci] === "Status" && typeof val === "string" && STATUS_COLOR[val];
                return (
                  <td key={ci} style={{ padding: "8px 12px", textAlign: table.numericCols.includes(ci) ? "right" : "left", borderBottom: `1px solid ${DOC_THEME.border}`, color: isStatus ? STATUS_COLOR[val as string] : DOC_THEME.text, fontWeight: isStatus ? 600 : 400, textTransform: isStatus ? "capitalize" : "none" }}>
                    {cellText(val, table.numericCols.includes(ci))}
                  </td>
                );
              })}
            </tr>
          ))}
        </tbody>
        {table.totals && (
          <tfoot>
            <tr>
              {table.totals.map((val, ci) => (
                <td key={ci} style={{ padding: "10px 12px", textAlign: table.numericCols.includes(ci) ? "right" : "left", background: "#E2F1ED", color: DOC_THEME.brandDark, fontWeight: 700, borderTop: `2px solid ${brand}` }}>
                  {cellText(val, table.numericCols.includes(ci))}
                </td>
              ))}
            </tr>
          </tfoot>
        )}
      </table>

      <div style={{ marginTop: 24, paddingTop: 12, borderTop: `1px solid ${DOC_THEME.border}`, fontSize: 11, color: DOC_THEME.muted, display: "flex", justifyContent: "space-between" }}>
        <span>{settings.companyName} — generated by Faraj OS</span>
        <span>{fmtDate(new Date())}</span>
      </div>

      <AutoPrint />
    </div>
  );
}
